### ISSUE TITLE
Piror data set problem

### ISSUE THREAD

**Issue by Wangjw6** [avisingh599/cog#2]
Does the prior dataset store the state-action pair in order?
How many independent trajectories in the prior dataset (e.g., pickplace_prior.npy)

Thank you!
Best

**Comment by avisingh599** [comment]
For future reference: 

1) Yes, they are in order. 
2) "For this simplified experimental setting, the prior data consists of 10K grasping attempts from a randomized scripted policy (that has a success rate of about 40%, details of this policy are in Appendix A.1)" in Section 6.1 of the paper (https://arxiv.org/pdf/2010.14500.pdf) 

Thanks,
Avi
