### ISSUE TITLE
Reproducibility Issue

### ISSUE THREAD

**Issue by shlee94** [avisingh599/cog#3]
Hi, 

I tried to reproduce the results from the paper, but failed to do so. 
Below are my attempts at reproducing the results (8 seeds, LHS) vs learning curves from the paper (RHS)

![tray](https://user-images.githubusercontent.com/29996836/118169170-9b961b80-b463-11eb-93c3-bafa13f40c9d.png)
![grasp_closed_drawer](https://user-images.githubusercontent.com/29996836/118169218-aa7cce00-b463-11eb-9379-cd0dffc940f7.png)

For the tray task, I am plotting "place_success_target Mean", and 
for the grasp task, I am plotting "grasp_success Mean",

Do I have to:
1. Use the reward transformation scheme?
2. Initialize the policy via BC?

Also, 
3. I'd appreciate it if you could clarify which log I have to keep track of for each task, e.g., am I tracking the right thing when I plot the "place_success_target Mean" for the tray task?

Thank you in advance!

**Comment by avisingh599** [comment]
Hi, 

The metrics you should be looking at are `evaluation/env_infos/final/place_success_target Mean` and `evaluation/env_infos/final/grasp_success Mean`. Note that the `final` here is important, which is probably what you are missing. The `final` bit ensures that the success condition is evaluated at the end of the trajectory (else, it might get evaluated at every timstep of the trajectory and averaged through, which will result in a lower success rate). 

Thank you for pointing out this issue. If you can confirm that this fixes your problem, I will add this info to the README.

**Comment by shlee94** [comment]
Hello, now I get the following:

![tray_new](https://user-images.githubusercontent.com/29996836/118441822-ae8b4300-b724-11eb-81e9-4a611063a5de.png)
Tray

![grasp_new](https://user-images.githubusercontent.com/29996836/118441845-b77c1480-b724-11eb-8ad1-c576b91faa78.png)
Grasp closed drawer

I assume the plots reported in the paper used some curve smoothing, but more or less I get the results from the paper!
Thanks for the help :)

One last question, did BC initialization and reward transformation (0,1) -> (4,6) have any positive effect on learning?

**Comment by avisingh599** [comment]
Glad you were able to reproduce the results!

I don't think either the BC initialization and the reward transformation were needed in the end -- we played around with them, but they were not required for the final results reported in the paper.
